### ISSUE TITLE
[FEATURE-REQUEST] Automatically infer checkalive job name or SBMJOB job name

### ISSUE THREAD

**Issue by ThePrez** [ThePrez/ServiceCommander-IBMi#54]
**Describe the solution you'd like**
Currently, if defining a service whose aliveness is checked by jobname, it's usually accomplished by submitting to batch with that job name. For instance:
```yaml
check_alive: jobname
check_alive_criteria: zookeeper
batch_mode: yes
sbmjob_jobname: zookeeper
```

This works great, but it is mildly annoying to have to specify the job name twice. It would be a good feature to automatically infer one of them based on the other. For instance, if a user could specify one of the following for the same result:

Option 1:
```yaml
check_alive: jobname
batch_mode: yes
sbmjob_jobname: zookeeper
```
Option 2:
```yaml
check_alive: jobname
check_alive_criteria: zookeeper
batch_mode: yes
```
`sc` need not support both ways. Option 1 is more elegant, but option 2 allows the user to specify a subsystem for `check_alive_criteria`

**Describe alternatives you've considered**
none

**Additional context**
This may introduce more confusion/complexity than it's worth.
